#pragma once
#include <string>

enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN, SEMICOLON, COMMA, IDENTIFIER, NUMBER,
    FUNCION, FIN, FIN_MIENTRAS, FIN_POR, HECHO,
    ENTERO, DECIMAL, CADENA, BOOLEANO, DEFINIR_PIN, SALIDA_KW, ENTRADA_KW,
    PRENDER, APAGAR, LEER, ESPERAR, MIENTRAS, SI, SINO, SINO_SI, POR,
    VERDADERO, FALSO, ASSIGN, OPERATOR, STRING_LITERAL, END_OF_FILE, COMMENT, ERROR
};

struct Token {
    TokenType type;
    std::string lexeme;
    int line;
};
